### PR TITLE
Fix broken links

### PR DESCRIPTION
**Pull request by fbaldo31**
Solve #13 for the moment.
Not sure to have to put this repositories here

### CODE REVIEW

**Comment by gdubcs** [comment]
I think it is best to use the binaries from our [cloned] release. That way it won't disappear if Mirantis ever feels like it...

**Comment by colintufts** [comment]
> I think it is best to use the binaries from our [cloned] release. That way it won't disappear if Mirantis ever feels like it... See #15

Agreed!

**Review by inquinity — APPROVED** [review]

**Comment by gdubcs** [comment]
Don't forget to revert the proxy url use our repo (`https://github.com/Open-Lens/lens-k8s-proxy/...`)

**Comment by fbaldo31** [comment]
> Don't forget to revert the proxy url to target our repo (`https://github.com/Open-Lens/lens-k8s-proxy/...`)

Did it this morning, please add your review as well

**Review by gdubcs — APPROVED** [review]

**Pull request merged**
